on:
  push:
    branches:
      - development
      - main
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Checkout the code
      - name: Log folder
        run: ls -la